### ISSUE TITLE
Subsequent approval requests declined

### ISSUE THREAD

**Issue by grod220** [prax-wallet/web#120]
After denial of approval popup, a second request gets swallowed without a response. It requires a page reload to reset the state to try again. This behavior has confused some external consumers. Todo: Do not require page reloads for subsequent requests.

https://github.com/user-attachments/assets/cfec112c-6a60-4550-b369-4ad074ac44a3

**Comment by turbocrime** [comment]
preventing repeat requests is deliberate - it makes spamming requests impossible, because a document can only make a request once in its lifecycle. each subsequent request will return the same result as the previous request, so an approved request will result in the success of all subsequent requests.

**Comment by grod220** [comment]
The current userflow in the video is one we can anticipate from all of the frontends. It feels broken. @plaidfinch, was able to work around this by triggering a full page reload upon denial. However, this feels quite hacky. We should have a more supported behavior for subsequent requests.

**Comment by turbocrime** [comment]
this is confirmed working

https://github.com/user-attachments/assets/35d88c36-916a-4e39-872c-0d924932f52c
